version: '3'

services:
  slack_machine:
    build: .
    restart: always
    network_mode: "host"
    env_file:
    - slack-machine.env
    depends_on:
    - "redis"
  redis:
    image: "redis:alpine"
    restart: always
    network_mode: "host"
